/**
 * 内容导出工具类
 * 用于将数据库内容导出为 Markdown 格式
 */

import db from './db';

/**
 * 格式化日期时间
 */
function formatDateTime(date: Date | string): string {
  const d = typeof date === 'string' ? new Date(date) : date;
  return d.toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  });
}

/**
 * 导出撰写计划为 Markdown
 */
export function exportPlanToMarkdown(projectId: number): string {
  try {
    const project = db.prepare('SELECT name FROM projects WHERE id = ?').get(projectId) as any;
    const plan = db.prepare('SELECT * FROM review_plans WHERE project_id = ? ORDER BY created_at DESC LIMIT 1').get(projectId) as any;

    if (!plan) {
      return '';
    }

    return `---
title: 文献综述撰写计划
project: ${project?.name || 'Unknown'}
created: ${plan.created_at}
---

# 文献综述撰写计划

**项目名称：** ${project?.name || 'Unknown'}
**创建时间：** ${formatDateTime(plan.created_at)}

## 计划内容

${plan.plan_content || '暂无内容'}

---
*Generated by Literature Review AI on ${formatDateTime(new Date())}*
`;
  } catch (error) {
    console.error('Failed to export plan:', error);
    return '';
  }
}

/**
 * 导出风格分析为 Markdown
 */
export function exportAnalysisToMarkdown(projectId: number): string {
  try {
    const project = db.prepare('SELECT name FROM projects WHERE id = ?').get(projectId) as any;
    const analysis = db.prepare('SELECT * FROM style_analysis WHERE project_id = ? ORDER BY created_at DESC LIMIT 1').get(projectId) as any;

    if (!analysis) {
      return '';
    }

    return `---
title: 写作风格分析报告
project: ${project?.name || 'Unknown'}
created: ${analysis.created_at}
---

# 写作风格分析报告

**项目名称：** ${project?.name || 'Unknown'}
**分析时间：** ${formatDateTime(analysis.created_at)}

## 分析结果

${analysis.analysis_result || '暂无分析结果'}

## 写作指南

${analysis.writing_guide || '暂无写作指南'}

---
*Generated by Literature Review AI on ${formatDateTime(new Date())}*
`;
  } catch (error) {
    console.error('Failed to export analysis:', error);
    return '';
  }
}

/**
 * 导出关键词为 Markdown
 */
export function exportKeywordsToMarkdown(projectId: number): string {
  try {
    const project = db.prepare('SELECT name FROM projects WHERE id = ?').get(projectId) as any;
    const keywords = db.prepare('SELECT * FROM project_keywords WHERE project_id = ?').all(projectId) as any[];

    if (!keywords || keywords.length === 0) {
      return '';
    }

    const keywordsList = keywords.map(k => `- ${k.keyword}`).join('\n');

    return `---
title: 项目关键词
project: ${project?.name || 'Unknown'}
updated: ${formatDateTime(new Date())}
---

# 项目关键词

**项目名称：** ${project?.name || 'Unknown'}
**更新时间：** ${formatDateTime(new Date())}
**关键词数量：** ${keywords.length}

## 关键词列表

${keywordsList}

---
*Generated by Literature Review AI on ${formatDateTime(new Date())}*
`;
  } catch (error) {
    console.error('Failed to export keywords:', error);
    return '';
  }
}

/**
 * 导出文献搜索结果为 Markdown
 */
export function exportSearchResultsToMarkdown(projectId: number): string {
  try {
    const project = db.prepare('SELECT name FROM projects WHERE id = ?').get(projectId) as any;
    const literature = db.prepare('SELECT * FROM searched_literature WHERE project_id = ? ORDER BY created_at DESC').all(projectId) as any[];

    if (!literature || literature.length === 0) {
      return '';
    }

    const literatureList = literature.map((lit, index) => {
      return `### ${index + 1}. ${lit.title || '无标题'}

- **作者：** ${lit.authors || '未知'}
- **来源：** ${lit.source || '未知'}
- **DOI：** ${lit.doi || '无'}
- **链接：** ${lit.url || '无'}
- **摘要：** ${lit.abstract || '无摘要'}
`;
    }).join('\n');

    return `---
title: 文献搜索结果
project: ${project?.name || 'Unknown'}
updated: ${formatDateTime(new Date())}
---

# 文献搜索结果

**项目名称：** ${project?.name || 'Unknown'}
**搜索时间：** ${formatDateTime(new Date())}
**文献数量：** ${literature.length}

## 文献列表

${literatureList}

---
*Generated by Literature Review AI on ${formatDateTime(new Date())}*
`;
  } catch (error) {
    console.error('Failed to export search results:', error);
    return '';
  }
}
